#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneUro.Depo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UrologyDb")]
	public partial class UrologyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDemografikOz(DemografikOz instance);
    partial void UpdateDemografikOz(DemografikOz instance);
    partial void DeleteDemografikOz(DemografikOz instance);
    partial void InsertTakipVerileri(TakipVerileri instance);
    partial void UpdateTakipVerileri(TakipVerileri instance);
    partial void DeleteTakipVerileri(TakipVerileri instance);
    partial void InsertDrListesi(DrListesi instance);
    partial void UpdateDrListesi(DrListesi instance);
    partial void DeleteDrListesi(DrListesi instance);
    partial void InsertHastaBilgi(HastaBilgi instance);
    partial void UpdateHastaBilgi(HastaBilgi instance);
    partial void DeleteHastaBilgi(HastaBilgi instance);
    partial void InsertOperasyonTuru(OperasyonTuru instance);
    partial void UpdateOperasyonTuru(OperasyonTuru instance);
    partial void DeleteOperasyonTuru(OperasyonTuru instance);
    partial void InsertOperatifOz(OperatifOz instance);
    partial void UpdateOperatifOz(OperatifOz instance);
    partial void DeleteOperatifOz(OperatifOz instance);
    partial void InsertPatolojikVeri(PatolojikVeri instance);
    partial void UpdatePatolojikVeri(PatolojikVeri instance);
    partial void DeletePatolojikVeri(PatolojikVeri instance);
    partial void InsertPosOperatifOz(PosOperatifOz instance);
    partial void UpdatePosOperatifOz(PosOperatifOz instance);
    partial void DeletePosOperatifOz(PosOperatifOz instance);
    #endregion
		
		public UrologyDataContext() : 
				base(global::HastaneUro.Properties.Settings.Default.UrologyDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UrologyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrologyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrologyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrologyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DemografikOz> DemografikOzs
		{
			get
			{
				return this.GetTable<DemografikOz>();
			}
		}
		
		public System.Data.Linq.Table<TakipVerileri> TakipVerileris
		{
			get
			{
				return this.GetTable<TakipVerileri>();
			}
		}
		
		public System.Data.Linq.Table<DrListesi> DrListesis
		{
			get
			{
				return this.GetTable<DrListesi>();
			}
		}
		
		public System.Data.Linq.Table<HastaBilgi> HastaBilgis
		{
			get
			{
				return this.GetTable<HastaBilgi>();
			}
		}
		
		public System.Data.Linq.Table<OperasyonTuru> OperasyonTurus
		{
			get
			{
				return this.GetTable<OperasyonTuru>();
			}
		}
		
		public System.Data.Linq.Table<OperatifOz> OperatifOzs
		{
			get
			{
				return this.GetTable<OperatifOz>();
			}
		}
		
		public System.Data.Linq.Table<PatolojikVeri> PatolojikVeris
		{
			get
			{
				return this.GetTable<PatolojikVeri>();
			}
		}
		
		public System.Data.Linq.Table<PosOperatifOz> PosOperatifOzs
		{
			get
			{
				return this.GetTable<PosOperatifOz>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DemografikOz")]
	public partial class DemografikOz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<int> _Boy;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<int> _BMI;
		
		private System.Nullable<int> _Asa;
		
		private string _Dr;
		
		private string _Cins;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private System.Nullable<int> _Boyut;
		
		private string _KoMorbidite;
		
		private EntityRef<HastaBilgi> _HastaBilgi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoyChanging(System.Nullable<int> value);
    partial void OnBoyChanged();
    partial void OnKiloChanging(System.Nullable<decimal> value);
    partial void OnKiloChanged();
    partial void OnBMIChanging(System.Nullable<int> value);
    partial void OnBMIChanged();
    partial void OnAsaChanging(System.Nullable<int> value);
    partial void OnAsaChanged();
    partial void OnDrChanging(string value);
    partial void OnDrChanged();
    partial void OnCinsChanging(string value);
    partial void OnCinsChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(System.Nullable<int> value);
    partial void OnBoyutChanged();
    partial void OnKoMorbiditeChanging(string value);
    partial void OnKoMorbiditeChanged();
    #endregion
		
		public DemografikOz()
		{
			this._HastaBilgi = default(EntityRef<HastaBilgi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._HastaBilgi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Int")]
		public System.Nullable<int> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Int")]
		public System.Nullable<int> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asa", DbType="Int")]
		public System.Nullable<int> Asa
		{
			get
			{
				return this._Asa;
			}
			set
			{
				if ((this._Asa != value))
				{
					this.OnAsaChanging(value);
					this.SendPropertyChanging();
					this._Asa = value;
					this.SendPropertyChanged("Asa");
					this.OnAsaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr", DbType="NVarChar(10)")]
		public string Dr
		{
			get
			{
				return this._Dr;
			}
			set
			{
				if ((this._Dr != value))
				{
					this.OnDrChanging(value);
					this.SendPropertyChanging();
					this._Dr = value;
					this.SendPropertyChanged("Dr");
					this.OnDrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cins", DbType="NVarChar(5)")]
		public string Cins
		{
			get
			{
				return this._Cins;
			}
			set
			{
				if ((this._Cins != value))
				{
					this.OnCinsChanging(value);
					this.SendPropertyChanging();
					this._Cins = value;
					this.SendPropertyChanged("Cins");
					this.OnCinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(5)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(50)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="Int")]
		public System.Nullable<int> Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoMorbidite", DbType="NVarChar(50)")]
		public string KoMorbidite
		{
			get
			{
				return this._KoMorbidite;
			}
			set
			{
				if ((this._KoMorbidite != value))
				{
					this.OnKoMorbiditeChanging(value);
					this.SendPropertyChanging();
					this._KoMorbidite = value;
					this.SendPropertyChanged("KoMorbidite");
					this.OnKoMorbiditeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_DemografikOz", Storage="_HastaBilgi", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public HastaBilgi HastaBilgi
		{
			get
			{
				return this._HastaBilgi.Entity;
			}
			set
			{
				HastaBilgi previousValue = this._HastaBilgi.Entity;
				if (((previousValue != value) 
							|| (this._HastaBilgi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HastaBilgi.Entity = null;
						previousValue.DemografikOzs.Remove(this);
					}
					this._HastaBilgi.Entity = value;
					if ((value != null))
					{
						value.DemografikOzs.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HastaBilgi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TakipVerileri")]
	public partial class TakipVerileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Portop3ayLokalNuks;
		
		private System.Nullable<decimal> _Portop3ayKreatin;
		
		private string _Portop6ayLokalNuks;
		
		private System.Nullable<decimal> _Portop6ayKreatin;
		
		private string _Portop12ayLokalNuks;
		
		private System.Nullable<decimal> _Portop12ayKreatin;
		
		private EntityRef<HastaBilgi> _HastaBilgi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPortop3ayLokalNuksChanging(string value);
    partial void OnPortop3ayLokalNuksChanged();
    partial void OnPortop3ayKreatinChanging(System.Nullable<decimal> value);
    partial void OnPortop3ayKreatinChanged();
    partial void OnPortop6ayLokalNuksChanging(string value);
    partial void OnPortop6ayLokalNuksChanged();
    partial void OnPortop6ayKreatinChanging(System.Nullable<decimal> value);
    partial void OnPortop6ayKreatinChanged();
    partial void OnPortop12ayLokalNuksChanging(string value);
    partial void OnPortop12ayLokalNuksChanged();
    partial void OnPortop12ayKreatinChanging(System.Nullable<decimal> value);
    partial void OnPortop12ayKreatinChanged();
    #endregion
		
		public TakipVerileri()
		{
			this._HastaBilgi = default(EntityRef<HastaBilgi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._HastaBilgi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portop3ayLokalNuks", DbType="NVarChar(10)")]
		public string Portop3ayLokalNuks
		{
			get
			{
				return this._Portop3ayLokalNuks;
			}
			set
			{
				if ((this._Portop3ayLokalNuks != value))
				{
					this.OnPortop3ayLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._Portop3ayLokalNuks = value;
					this.SendPropertyChanged("Portop3ayLokalNuks");
					this.OnPortop3ayLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portop3ayKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Portop3ayKreatin
		{
			get
			{
				return this._Portop3ayKreatin;
			}
			set
			{
				if ((this._Portop3ayKreatin != value))
				{
					this.OnPortop3ayKreatinChanging(value);
					this.SendPropertyChanging();
					this._Portop3ayKreatin = value;
					this.SendPropertyChanged("Portop3ayKreatin");
					this.OnPortop3ayKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portop6ayLokalNuks", DbType="NVarChar(10)")]
		public string Portop6ayLokalNuks
		{
			get
			{
				return this._Portop6ayLokalNuks;
			}
			set
			{
				if ((this._Portop6ayLokalNuks != value))
				{
					this.OnPortop6ayLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._Portop6ayLokalNuks = value;
					this.SendPropertyChanged("Portop6ayLokalNuks");
					this.OnPortop6ayLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portop6ayKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Portop6ayKreatin
		{
			get
			{
				return this._Portop6ayKreatin;
			}
			set
			{
				if ((this._Portop6ayKreatin != value))
				{
					this.OnPortop6ayKreatinChanging(value);
					this.SendPropertyChanging();
					this._Portop6ayKreatin = value;
					this.SendPropertyChanged("Portop6ayKreatin");
					this.OnPortop6ayKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portop12ayLokalNuks", DbType="NVarChar(10)")]
		public string Portop12ayLokalNuks
		{
			get
			{
				return this._Portop12ayLokalNuks;
			}
			set
			{
				if ((this._Portop12ayLokalNuks != value))
				{
					this.OnPortop12ayLokalNuksChanging(value);
					this.SendPropertyChanging();
					this._Portop12ayLokalNuks = value;
					this.SendPropertyChanged("Portop12ayLokalNuks");
					this.OnPortop12ayLokalNuksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portop12ayKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Portop12ayKreatin
		{
			get
			{
				return this._Portop12ayKreatin;
			}
			set
			{
				if ((this._Portop12ayKreatin != value))
				{
					this.OnPortop12ayKreatinChanging(value);
					this.SendPropertyChanging();
					this._Portop12ayKreatin = value;
					this.SendPropertyChanged("Portop12ayKreatin");
					this.OnPortop12ayKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_TakipVerileri", Storage="_HastaBilgi", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public HastaBilgi HastaBilgi
		{
			get
			{
				return this._HastaBilgi.Entity;
			}
			set
			{
				HastaBilgi previousValue = this._HastaBilgi.Entity;
				if (((previousValue != value) 
							|| (this._HastaBilgi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HastaBilgi.Entity = null;
						previousValue.TakipVerileris.Remove(this);
					}
					this._HastaBilgi.Entity = value;
					if ((value != null))
					{
						value.TakipVerileris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HastaBilgi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DrListesi")]
	public partial class DrListesi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DrAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDrAdiChanging(string value);
    partial void OnDrAdiChanged();
    #endregion
		
		public DrListesi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrAdi", DbType="NVarChar(50)")]
		public string DrAdi
		{
			get
			{
				return this._DrAdi;
			}
			set
			{
				if ((this._DrAdi != value))
				{
					this.OnDrAdiChanging(value);
					this.SendPropertyChanging();
					this._DrAdi = value;
					this.SendPropertyChanged("DrAdi");
					this.OnDrAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HastaBilgi")]
	public partial class HastaBilgi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaNo;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Protokol;
		
		private System.Nullable<System.DateTime> _OpTarih;
		
		private string _OpTuru;
		
		private System.Nullable<int> _Takip;
		
		private System.Nullable<int> _Anah;
		
		private EntitySet<DemografikOz> _DemografikOzs;
		
		private EntitySet<TakipVerileri> _TakipVerileris;
		
		private EntitySet<OperatifOz> _OperatifOzs;
		
		private EntitySet<PatolojikVeri> _PatolojikVeris;
		
		private EntitySet<PosOperatifOz> _PosOperatifOzs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaNoChanging(System.Nullable<int> value);
    partial void OnHastaNoChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnProtokolChanging(string value);
    partial void OnProtokolChanged();
    partial void OnOpTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnOpTarihChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    partial void OnTakipChanging(System.Nullable<int> value);
    partial void OnTakipChanged();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    #endregion
		
		public HastaBilgi()
		{
			this._DemografikOzs = new EntitySet<DemografikOz>(new Action<DemografikOz>(this.attach_DemografikOzs), new Action<DemografikOz>(this.detach_DemografikOzs));
			this._TakipVerileris = new EntitySet<TakipVerileri>(new Action<TakipVerileri>(this.attach_TakipVerileris), new Action<TakipVerileri>(this.detach_TakipVerileris));
			this._OperatifOzs = new EntitySet<OperatifOz>(new Action<OperatifOz>(this.attach_OperatifOzs), new Action<OperatifOz>(this.detach_OperatifOzs));
			this._PatolojikVeris = new EntitySet<PatolojikVeri>(new Action<PatolojikVeri>(this.attach_PatolojikVeris), new Action<PatolojikVeri>(this.detach_PatolojikVeris));
			this._PosOperatifOzs = new EntitySet<PosOperatifOz>(new Action<PosOperatifOz>(this.attach_PosOperatifOzs), new Action<PosOperatifOz>(this.detach_PosOperatifOzs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaNo", DbType="Int")]
		public System.Nullable<int> HastaNo
		{
			get
			{
				return this._HastaNo;
			}
			set
			{
				if ((this._HastaNo != value))
				{
					this.OnHastaNoChanging(value);
					this.SendPropertyChanging();
					this._HastaNo = value;
					this.SendPropertyChanged("HastaNo");
					this.OnHastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(20)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(20)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protokol", DbType="NVarChar(50)")]
		public string Protokol
		{
			get
			{
				return this._Protokol;
			}
			set
			{
				if ((this._Protokol != value))
				{
					this.OnProtokolChanging(value);
					this.SendPropertyChanging();
					this._Protokol = value;
					this.SendPropertyChanged("Protokol");
					this.OnProtokolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> OpTarih
		{
			get
			{
				return this._OpTarih;
			}
			set
			{
				if ((this._OpTarih != value))
				{
					this.OnOpTarihChanging(value);
					this.SendPropertyChanging();
					this._OpTarih = value;
					this.SendPropertyChanged("OpTarih");
					this.OnOpTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(50)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="Int")]
		public System.Nullable<int> Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_DemografikOz", Storage="_DemografikOzs", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<DemografikOz> DemografikOzs
		{
			get
			{
				return this._DemografikOzs;
			}
			set
			{
				this._DemografikOzs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_TakipVerileri", Storage="_TakipVerileris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<TakipVerileri> TakipVerileris
		{
			get
			{
				return this._TakipVerileris;
			}
			set
			{
				this._TakipVerileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_OperatifOz", Storage="_OperatifOzs", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<OperatifOz> OperatifOzs
		{
			get
			{
				return this._OperatifOzs;
			}
			set
			{
				this._OperatifOzs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_PatolojikVeri", Storage="_PatolojikVeris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<PatolojikVeri> PatolojikVeris
		{
			get
			{
				return this._PatolojikVeris;
			}
			set
			{
				this._PatolojikVeris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_PosOperatifOz", Storage="_PosOperatifOzs", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<PosOperatifOz> PosOperatifOzs
		{
			get
			{
				return this._PosOperatifOzs;
			}
			set
			{
				this._PosOperatifOzs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DemografikOzs(DemografikOz entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = this;
		}
		
		private void detach_DemografikOzs(DemografikOz entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = null;
		}
		
		private void attach_TakipVerileris(TakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = this;
		}
		
		private void detach_TakipVerileris(TakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = null;
		}
		
		private void attach_OperatifOzs(OperatifOz entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = this;
		}
		
		private void detach_OperatifOzs(OperatifOz entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = null;
		}
		
		private void attach_PatolojikVeris(PatolojikVeri entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = this;
		}
		
		private void detach_PatolojikVeris(PatolojikVeri entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = null;
		}
		
		private void attach_PosOperatifOzs(PosOperatifOz entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = this;
		}
		
		private void detach_PosOperatifOzs(PosOperatifOz entity)
		{
			this.SendPropertyChanging();
			entity.HastaBilgi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OperasyonTuru")]
	public partial class OperasyonTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OpTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    #endregion
		
		public OperasyonTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(50)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OperatifOz")]
	public partial class OperatifOz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PksAcıklama;
		
		private string _Sik;
		
		private string _CoOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardımYnt;
		
		private System.Nullable<int> _Sure;
		
		private string _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private string _Piyes;
		
		private EntityRef<HastaBilgi> _HastaBilgi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPksAcıklamaChanging(string value);
    partial void OnPksAcıklamaChanged();
    partial void OnSikChanging(string value);
    partial void OnSikChanged();
    partial void OnCoOperasyonChanging(string value);
    partial void OnCoOperasyonChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortSayisiChanging(System.Nullable<int> value);
    partial void OnPortSayisiChanged();
    partial void OnYardımYntChanging(string value);
    partial void OnYardımYntChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(string value);
    partial void OnPiyesChanged();
    #endregion
		
		public OperatifOz()
		{
			this._HastaBilgi = default(EntityRef<HastaBilgi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._HastaBilgi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAcıklama", DbType="NVarChar(10)")]
		public string PksAcıklama
		{
			get
			{
				return this._PksAcıklama;
			}
			set
			{
				if ((this._PksAcıklama != value))
				{
					this.OnPksAcıklamaChanging(value);
					this.SendPropertyChanging();
					this._PksAcıklama = value;
					this.SendPropertyChanged("PksAcıklama");
					this.OnPksAcıklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sik", DbType="NVarChar(20)")]
		public string Sik
		{
			get
			{
				return this._Sik;
			}
			set
			{
				if ((this._Sik != value))
				{
					this.OnSikChanging(value);
					this.SendPropertyChanging();
					this._Sik = value;
					this.SendPropertyChanged("Sik");
					this.OnSikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoOperasyon", DbType="NVarChar(50)")]
		public string CoOperasyon
		{
			get
			{
				return this._CoOperasyon;
			}
			set
			{
				if ((this._CoOperasyon != value))
				{
					this.OnCoOperasyonChanging(value);
					this.SendPropertyChanging();
					this._CoOperasyon = value;
					this.SendPropertyChanged("CoOperasyon");
					this.OnCoOperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this.OnPortSayisiChanging(value);
					this.SendPropertyChanging();
					this._PortSayisi = value;
					this.SendPropertyChanged("PortSayisi");
					this.OnPortSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardımYnt", DbType="NVarChar(50)")]
		public string YardımYnt
		{
			get
			{
				return this._YardımYnt;
			}
			set
			{
				if ((this._YardımYnt != value))
				{
					this.OnYardımYntChanging(value);
					this.SendPropertyChanging();
					this._YardımYnt = value;
					this.SendPropertyChanged("YardımYnt");
					this.OnYardımYntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(10)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="NVarChar(50)")]
		public string Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_OperatifOz", Storage="_HastaBilgi", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public HastaBilgi HastaBilgi
		{
			get
			{
				return this._HastaBilgi.Entity;
			}
			set
			{
				HastaBilgi previousValue = this._HastaBilgi.Entity;
				if (((previousValue != value) 
							|| (this._HastaBilgi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HastaBilgi.Entity = null;
						previousValue.OperatifOzs.Remove(this);
					}
					this._HastaBilgi.Entity = value;
					if ((value != null))
					{
						value.OperatifOzs.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HastaBilgi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatolojikVeri")]
	public partial class PatolojikVeri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private string _FurhmanGrade;
		
		private string _PatolojikEvre;
		
		private string _CerrahiSinir;
		
		private EntityRef<HastaBilgi> _HastaBilgi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    partial void OnFurhmanGradeChanging(string value);
    partial void OnFurhmanGradeChanged();
    partial void OnPatolojikEvreChanging(string value);
    partial void OnPatolojikEvreChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public PatolojikVeri()
		{
			this._HastaBilgi = default(EntityRef<HastaBilgi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._HastaBilgi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(50)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FurhmanGrade", DbType="NVarChar(50)")]
		public string FurhmanGrade
		{
			get
			{
				return this._FurhmanGrade;
			}
			set
			{
				if ((this._FurhmanGrade != value))
				{
					this.OnFurhmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FurhmanGrade = value;
					this.SendPropertyChanged("FurhmanGrade");
					this.OnFurhmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvre", DbType="NVarChar(10)")]
		public string PatolojikEvre
		{
			get
			{
				return this._PatolojikEvre;
			}
			set
			{
				if ((this._PatolojikEvre != value))
				{
					this.OnPatolojikEvreChanging(value);
					this.SendPropertyChanging();
					this._PatolojikEvre = value;
					this.SendPropertyChanged("PatolojikEvre");
					this.OnPatolojikEvreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(10)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_PatolojikVeri", Storage="_HastaBilgi", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public HastaBilgi HastaBilgi
		{
			get
			{
				return this._HastaBilgi.Entity;
			}
			set
			{
				HastaBilgi previousValue = this._HastaBilgi.Entity;
				if (((previousValue != value) 
							|| (this._HastaBilgi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HastaBilgi.Entity = null;
						previousValue.PatolojikVeris.Remove(this);
					}
					this._HastaBilgi.Entity = value;
					if ((value != null))
					{
						value.PatolojikVeris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HastaBilgi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PosOperatifOz")]
	public partial class PosOperatifOz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PeropVeErkenKomp;
		
		private string _Dren;
		
		private string _PostopAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PreopKreatin;
		
		private System.Nullable<decimal> _PostopKreatin;
		
		private System.Nullable<decimal> _PreopHct;
		
		private System.Nullable<decimal> _PostopHct;
		
		private System.Nullable<decimal> _PreopHb;
		
		private System.Nullable<decimal> _PostopHb;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostopGecKomp;
		
		private string _KompClavien;
		
		private EntityRef<HastaBilgi> _HastaBilgi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPeropVeErkenKompChanging(string value);
    partial void OnPeropVeErkenKompChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnPostopAnalizChanging(string value);
    partial void OnPostopAnalizChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSuresiChanging(System.Nullable<int> value);
    partial void OnHospSuresiChanged();
    partial void OnPreopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPreopKreatinChanged();
    partial void OnPostopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostopKreatinChanged();
    partial void OnPreopHctChanging(System.Nullable<decimal> value);
    partial void OnPreopHctChanged();
    partial void OnPostopHctChanging(System.Nullable<decimal> value);
    partial void OnPostopHctChanged();
    partial void OnPreopHbChanging(System.Nullable<decimal> value);
    partial void OnPreopHbChanged();
    partial void OnPostopHbChanging(System.Nullable<decimal> value);
    partial void OnPostopHbChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostopGecKompChanging(string value);
    partial void OnPostopGecKompChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    #endregion
		
		public PosOperatifOz()
		{
			this._HastaBilgi = default(EntityRef<HastaBilgi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._HastaBilgi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeropVeErkenKomp", DbType="NVarChar(50)")]
		public string PeropVeErkenKomp
		{
			get
			{
				return this._PeropVeErkenKomp;
			}
			set
			{
				if ((this._PeropVeErkenKomp != value))
				{
					this.OnPeropVeErkenKompChanging(value);
					this.SendPropertyChanging();
					this._PeropVeErkenKomp = value;
					this.SendPropertyChanged("PeropVeErkenKomp");
					this.OnPeropVeErkenKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(10)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopAnaliz", DbType="NVarChar(200)")]
		public string PostopAnaliz
		{
			get
			{
				return this._PostopAnaliz;
			}
			set
			{
				if ((this._PostopAnaliz != value))
				{
					this.OnPostopAnalizChanging(value);
					this.SendPropertyChanging();
					this._PostopAnaliz = value;
					this.SendPropertyChanged("PostopAnaliz");
					this.OnPostopAnalizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(20)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this.OnHospSuresiChanging(value);
					this.SendPropertyChanging();
					this._HospSuresi = value;
					this.SendPropertyChanged("HospSuresi");
					this.OnHospSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> PreopKreatin
		{
			get
			{
				return this._PreopKreatin;
			}
			set
			{
				if ((this._PreopKreatin != value))
				{
					this.OnPreopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PreopKreatin = value;
					this.SendPropertyChanged("PreopKreatin");
					this.OnPreopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopKreatin", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PostopKreatin
		{
			get
			{
				return this._PostopKreatin;
			}
			set
			{
				if ((this._PostopKreatin != value))
				{
					this.OnPostopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostopKreatin = value;
					this.SendPropertyChanged("PostopKreatin");
					this.OnPostopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHct", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreopHct
		{
			get
			{
				return this._PreopHct;
			}
			set
			{
				if ((this._PreopHct != value))
				{
					this.OnPreopHctChanging(value);
					this.SendPropertyChanging();
					this._PreopHct = value;
					this.SendPropertyChanged("PreopHct");
					this.OnPreopHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHct", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostopHct
		{
			get
			{
				return this._PostopHct;
			}
			set
			{
				if ((this._PostopHct != value))
				{
					this.OnPostopHctChanging(value);
					this.SendPropertyChanging();
					this._PostopHct = value;
					this.SendPropertyChanged("PostopHct");
					this.OnPostopHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHb", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PreopHb
		{
			get
			{
				return this._PreopHb;
			}
			set
			{
				if ((this._PreopHb != value))
				{
					this.OnPreopHbChanging(value);
					this.SendPropertyChanging();
					this._PreopHb = value;
					this.SendPropertyChanged("PreopHb");
					this.OnPreopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHb", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostopHb
		{
			get
			{
				return this._PostopHb;
			}
			set
			{
				if ((this._PostopHb != value))
				{
					this.OnPostopHbChanging(value);
					this.SendPropertyChanging();
					this._PostopHb = value;
					this.SendPropertyChanged("PostopHb");
					this.OnPostopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(50)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopGecKomp", DbType="NVarChar(50)")]
		public string PostopGecKomp
		{
			get
			{
				return this._PostopGecKomp;
			}
			set
			{
				if ((this._PostopGecKomp != value))
				{
					this.OnPostopGecKompChanging(value);
					this.SendPropertyChanging();
					this._PostopGecKomp = value;
					this.SendPropertyChanged("PostopGecKomp");
					this.OnPostopGecKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(10)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HastaBilgi_PosOperatifOz", Storage="_HastaBilgi", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public HastaBilgi HastaBilgi
		{
			get
			{
				return this._HastaBilgi.Entity;
			}
			set
			{
				HastaBilgi previousValue = this._HastaBilgi.Entity;
				if (((previousValue != value) 
							|| (this._HastaBilgi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HastaBilgi.Entity = null;
						previousValue.PosOperatifOzs.Remove(this);
					}
					this._HastaBilgi.Entity = value;
					if ((value != null))
					{
						value.PosOperatifOzs.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HastaBilgi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
